#!/bin/bash
#SBATCH --job-name=maule-datagen
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=240000MB
#SBATCH --time=48:00:00
#SBATCH --output=/path/to/TREMOR/dataprep/maule/logs/%x.%A_%a.out
#SBATCH --error=/path/to/TREMOR/dataprep/maule/logs/%x.%A_%a.err

set -euo pipefail
export OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1

export MAULE_RUN_LABEL="${MAULE_RUN_LABEL:-maule-datagen}"

echo "RunLabel $MAULE_RUN_LABEL"
echo "JobID ${SLURM_JOB_ID:-none}"
echo "ArrayTaskID ${SLURM_ARRAY_TASK_ID:-none}"
echo "Running on: ${SLURM_NODELIST:-unknown}"
echo "SLURM_NTASKS=${SLURM_NTASKS:-}"
echo "SLURM_CPUS_PER_TASK=${SLURM_CPUS_PER_TASK:-}"
echo "SLURM_CPUS_ON_NODE=${SLURM_CPUS_ON_NODE:-}"
echo "SLURM_MEM_PER_NODE=${SLURM_MEM_PER_NODE:-}"

module purge || true

source ~/.bashrc
conda activate "${CONDA_ENV:-base}"  # a Python environment with NumPy, ObsPy and Matplotlib

cd /path/to/TREMOR

export MPLCONFIGDIR="${MPLCONFIGDIR:-/tmp/matplotlib-${SLURM_JOB_ID:-maule-datagen}}"
mkdir -p "$MPLCONFIGDIR"

export MAULE_SDS_ROOT="${MAULE_SDS_ROOT:-/path/to/raw/maule/SDS/}"
export MAULE_WAVEFORM_OUTPUT_DIR="${MAULE_WAVEFORM_OUTPUT_DIR:-/path/to/data/maule/waveforms/}"
export MAULE_TEMPLATE_OUTPUT_DIR="${MAULE_TEMPLATE_OUTPUT_DIR:-/path/to/data/maule/templates/}"
export MAULE_SUMMARY_OUTPUT_DIR="${MAULE_SUMMARY_OUTPUT_DIR:-/path/to/TREMOR/dataprep/maule/metadata/}"
export MAULE_SLURM_LOG_DIR="${MAULE_SLURM_LOG_DIR:-/path/to/TREMOR/dataprep/maule/logs}"

# Process one day per chunk to keep ObsPy/SciPy memory bounded.
export MAULE_GENERATION_CHUNK_DAYS="${MAULE_GENERATION_CHUNK_DAYS:-1}"
export MAULE_FILTER_FMIN="${MAULE_FILTER_FMIN:-1}"
export MAULE_FILTER_FMAX="${MAULE_FILTER_FMAX:-10}"
export MAULE_DOWNSAMPLE_FACTOR="${MAULE_DOWNSAMPLE_FACTOR:-2}"

# Leave unset for the full available SDS range. Useful for smoke tests:
# export MAULE_GENERATION_MAX_DAYS=2

# Leave unset to process all selected entries. Useful for smoke tests:
# export MAULE_MAX_GENERATION_ENTRIES=1

# Slurm array support. If you submit with --array=0-23, the 24 tasks split
# the selected station/channel entries by index modulo 24.
if [[ -n "${SLURM_ARRAY_TASK_ID:-}" ]]; then
    export MAULE_GENERATION_ENTRY_OFFSET="${MAULE_GENERATION_ENTRY_OFFSET:-$SLURM_ARRAY_TASK_ID}"
    export MAULE_GENERATION_ENTRY_STRIDE="${MAULE_GENERATION_ENTRY_STRIDE:-${SLURM_ARRAY_TASK_COUNT:-1}}"
else
    export MAULE_GENERATION_ENTRY_OFFSET="${MAULE_GENERATION_ENTRY_OFFSET:-0}"
    export MAULE_GENERATION_ENTRY_STRIDE="${MAULE_GENERATION_ENTRY_STRIDE:-1}"
fi

export RUN_WAVEFORMS="${RUN_WAVEFORMS:-0}"
export RUN_TEMPLATES="${RUN_TEMPLATES:-1}"
export MAULE_ENABLE_WAVEFORM_REPORT="${MAULE_ENABLE_WAVEFORM_REPORT:-1}"
export MAULE_ENABLE_TEMPLATE_REPORT="${MAULE_ENABLE_TEMPLATE_REPORT:-1}"
export MAULE_WAVEFORM_PLOT_MAX_POINTS="${MAULE_WAVEFORM_PLOT_MAX_POINTS:-200000}"
export MAULE_WAVEFORM_PLOT_POINTS_PER_CHUNK="${MAULE_WAVEFORM_PLOT_POINTS_PER_CHUNK:-4000}"
export MAULE_TEMPLATE_REPORT_ROW_PREVIEW_LIMIT="${MAULE_TEMPLATE_REPORT_ROW_PREVIEW_LIMIT:-20}"
export MAULE_TEMPLATE_PLOT_SAMPLE_COUNT="${MAULE_TEMPLATE_PLOT_SAMPLE_COUNT:-5}"
export MAULE_TEMPLATE_PLOT_SEED="${MAULE_TEMPLATE_PLOT_SEED:-0}"

mkdir -p "$MAULE_SLURM_LOG_DIR"
mkdir -p "$MAULE_WAVEFORM_OUTPUT_DIR" "$MAULE_TEMPLATE_OUTPUT_DIR" "$MAULE_SUMMARY_OUTPUT_DIR"

echo "MAULE_SDS_ROOT=$MAULE_SDS_ROOT"
echo "MAULE_WAVEFORM_OUTPUT_DIR=$MAULE_WAVEFORM_OUTPUT_DIR"
echo "MAULE_TEMPLATE_OUTPUT_DIR=$MAULE_TEMPLATE_OUTPUT_DIR"
echo "MAULE_SUMMARY_OUTPUT_DIR=$MAULE_SUMMARY_OUTPUT_DIR"
echo "MAULE_SLURM_LOG_DIR=$MAULE_SLURM_LOG_DIR"
echo "MAULE_GENERATION_CHUNK_DAYS=$MAULE_GENERATION_CHUNK_DAYS"
echo "MAULE_FILTER_FMIN=$MAULE_FILTER_FMIN"
echo "MAULE_FILTER_FMAX=$MAULE_FILTER_FMAX"
echo "MAULE_DOWNSAMPLE_FACTOR=$MAULE_DOWNSAMPLE_FACTOR"
echo "MAULE_GENERATION_MAX_DAYS=${MAULE_GENERATION_MAX_DAYS:-unset}"
echo "MAULE_MAX_GENERATION_ENTRIES=${MAULE_MAX_GENERATION_ENTRIES:-unset}"
echo "MAULE_GENERATION_ENTRY_OFFSET=$MAULE_GENERATION_ENTRY_OFFSET"
echo "MAULE_GENERATION_ENTRY_STRIDE=$MAULE_GENERATION_ENTRY_STRIDE"
echo "MAULE_ENABLE_WAVEFORM_REPORT=$MAULE_ENABLE_WAVEFORM_REPORT"
echo "MAULE_ENABLE_TEMPLATE_REPORT=$MAULE_ENABLE_TEMPLATE_REPORT"
echo "MAULE_WAVEFORM_PLOT_MAX_POINTS=$MAULE_WAVEFORM_PLOT_MAX_POINTS"
echo "MAULE_WAVEFORM_PLOT_POINTS_PER_CHUNK=$MAULE_WAVEFORM_PLOT_POINTS_PER_CHUNK"
echo "MAULE_TEMPLATE_REPORT_ROW_PREVIEW_LIMIT=$MAULE_TEMPLATE_REPORT_ROW_PREVIEW_LIMIT"
echo "MAULE_TEMPLATE_PLOT_SAMPLE_COUNT=$MAULE_TEMPLATE_PLOT_SAMPLE_COUNT"
echo "MAULE_TEMPLATE_PLOT_SEED=$MAULE_TEMPLATE_PLOT_SEED"
echo "RUN_WAVEFORMS=$RUN_WAVEFORMS"
echo "RUN_TEMPLATES=$RUN_TEMPLATES"

if [[ "$RUN_WAVEFORMS" == "1" ]]; then
    echo ""
    echo ">> Generating waveform binaries"
    python dataprep/maule/data_generator.py
fi

if [[ "$RUN_TEMPLATES" == "1" ]]; then
    echo ""
    echo ">> Generating template binaries"
    export MAULE_TEMPLATE_TASK_ID="${SLURM_ARRAY_TASK_ID:-0}"
    export MAULE_TEMPLATE_TASK_COUNT="${SLURM_ARRAY_TASK_COUNT:-1}"
    python dataprep/maule/readcsvtemplates.py
fi

echo ""
echo "Done."
