#!/bin/bash
#SBATCH --job-name=seifr-datagen
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=240000MB
#SBATCH --time=48:00:00
#SBATCH --output=/path/to/TREMOR/dataprep/seiFR/logs/%x.%A_%a.out
#SBATCH --error=/path/to/TREMOR/dataprep/seiFR/logs/%x.%A_%a.err

set -euo pipefail
export OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1

export SEIFR_RUN_LABEL="${SEIFR_RUN_LABEL:-seifr-datagen}"

echo "RunLabel $SEIFR_RUN_LABEL"
echo "JobID ${SLURM_JOB_ID:-none}"
echo "ArrayTaskID ${SLURM_ARRAY_TASK_ID:-none}"
echo "Running on: ${SLURM_NODELIST:-unknown}"
echo "SLURM_NTASKS=${SLURM_NTASKS:-}"
echo "SLURM_CPUS_PER_TASK=${SLURM_CPUS_PER_TASK:-}"
echo "SLURM_CPUS_ON_NODE=${SLURM_CPUS_ON_NODE:-}"
echo "SLURM_MEM_PER_NODE=${SLURM_MEM_PER_NODE:-}"

module purge || true

source ~/.bashrc
conda activate "${CONDA_ENV:-base}"  # a Python environment with NumPy, ObsPy and Matplotlib

cd /path/to/TREMOR

export MPLCONFIGDIR="${MPLCONFIGDIR:-/tmp/matplotlib-${SLURM_JOB_ID:-seifr-datagen}}"
mkdir -p "$MPLCONFIGDIR"

export SEIFR_SDS_ROOT="${SEIFR_SDS_ROOT:-/path/to/raw/seifr/SDS/}"
export SEIFR_WAVEFORM_OUTPUT_DIR="${SEIFR_WAVEFORM_OUTPUT_DIR:-/path/to/data/seifr/waveforms/}"
export SEIFR_TEMPLATE_OUTPUT_DIR="${SEIFR_TEMPLATE_OUTPUT_DIR:-/path/to/data/seifr/templates/}"
export SEIFR_EVENTS_QML="${SEIFR_EVENTS_QML:-/path/to/raw/seifr/event.qml}"
export SEIFR_SUMMARY_OUTPUT_DIR="${SEIFR_SUMMARY_OUTPUT_DIR:-/path/to/TREMOR/dataprep/seiFR/metadata/}"
export SEIFR_SLURM_LOG_DIR="${SEIFR_SLURM_LOG_DIR:-/path/to/TREMOR/dataprep/seiFR/logs}"
export SEIFR_CHANNEL_PREFIXES="${SEIFR_CHANNEL_PREFIXES:-BH}"

# Process one day per chunk to keep ObsPy/SciPy memory bounded.
export SEIFR_GENERATION_CHUNK_DAYS="${SEIFR_GENERATION_CHUNK_DAYS:-1}"
export SEIFR_FILTER_FMIN="${SEIFR_FILTER_FMIN:-1}"
export SEIFR_FILTER_FMAX="${SEIFR_FILTER_FMAX:-10}"
export SEIFR_DOWNSAMPLE_FACTOR="${SEIFR_DOWNSAMPLE_FACTOR:-2}"

# Leave unset for the full available selected interval. Useful for smoke tests:
# export SEIFR_GENERATION_MAX_DAYS=2

# Leave unset to process all selected entries. Useful for smoke tests:
# export SEIFR_MAX_GENERATION_ENTRIES=1

# Default French dataset window used by datagen.py.
export SEIFR_START_DATE="${SEIFR_START_DATE:-2020-1-1}"
export SEIFR_DAYS_TO_LOAD="${SEIFR_DAYS_TO_LOAD:-730}"

if [[ -n "${SLURM_ARRAY_TASK_ID:-}" ]]; then
    export SEIFR_GENERATION_ENTRY_OFFSET="${SEIFR_GENERATION_ENTRY_OFFSET:-$SLURM_ARRAY_TASK_ID}"
    export SEIFR_GENERATION_ENTRY_STRIDE="${SEIFR_GENERATION_ENTRY_STRIDE:-${SLURM_ARRAY_TASK_COUNT:-1}}"
else
    export SEIFR_GENERATION_ENTRY_OFFSET="${SEIFR_GENERATION_ENTRY_OFFSET:-0}"
    export SEIFR_GENERATION_ENTRY_STRIDE="${SEIFR_GENERATION_ENTRY_STRIDE:-1}"
fi

export RUN_WAVEFORMS="${RUN_WAVEFORMS:-1}"
export RUN_TEMPLATES="${RUN_TEMPLATES:-0}"
export SEIFR_ENABLE_INVENTORY_REPORT="${SEIFR_ENABLE_INVENTORY_REPORT:-0}"
export SEIFR_ENABLE_WAVEFORM_REPORT="${SEIFR_ENABLE_WAVEFORM_REPORT:-1}"
export SEIFR_ENABLE_TEMPLATE_REPORT="${SEIFR_ENABLE_TEMPLATE_REPORT:-1}"
export SEIFR_WAVEFORM_PLOT_MAX_POINTS="${SEIFR_WAVEFORM_PLOT_MAX_POINTS:-200000}"
export SEIFR_WAVEFORM_PLOT_POINTS_PER_CHUNK="${SEIFR_WAVEFORM_PLOT_POINTS_PER_CHUNK:-4000}"
export SEIFR_TEMPLATE_SOURCE="${SEIFR_TEMPLATE_SOURCE:-auto}"
export SEIFR_TEMPLATE_WINDOW_LENGTH_SEC="${SEIFR_TEMPLATE_WINDOW_LENGTH_SEC:-120}"
export SEIFR_TEMPLATE_LEAD_TIME_SEC="${SEIFR_TEMPLATE_LEAD_TIME_SEC:-2}"
export SEIFR_TEMPLATE_REPORT_ROW_PREVIEW_LIMIT="${SEIFR_TEMPLATE_REPORT_ROW_PREVIEW_LIMIT:-20}"
export SEIFR_TEMPLATE_PLOT_SAMPLE_COUNT="${SEIFR_TEMPLATE_PLOT_SAMPLE_COUNT:-5}"
export SEIFR_TEMPLATE_PLOT_SEED="${SEIFR_TEMPLATE_PLOT_SEED:-0}"

mkdir -p "$SEIFR_SLURM_LOG_DIR"
mkdir -p "$SEIFR_WAVEFORM_OUTPUT_DIR" "$SEIFR_TEMPLATE_OUTPUT_DIR" "$SEIFR_SUMMARY_OUTPUT_DIR"

echo "SEIFR_SDS_ROOT=$SEIFR_SDS_ROOT"
echo "SEIFR_WAVEFORM_OUTPUT_DIR=$SEIFR_WAVEFORM_OUTPUT_DIR"
echo "SEIFR_TEMPLATE_OUTPUT_DIR=$SEIFR_TEMPLATE_OUTPUT_DIR"
echo "SEIFR_EVENTS_QML=$SEIFR_EVENTS_QML"
echo "SEIFR_SUMMARY_OUTPUT_DIR=$SEIFR_SUMMARY_OUTPUT_DIR"
echo "SEIFR_SLURM_LOG_DIR=$SEIFR_SLURM_LOG_DIR"
echo "SEIFR_CHANNEL_PREFIXES=$SEIFR_CHANNEL_PREFIXES"
echo "SEIFR_GENERATION_CHUNK_DAYS=$SEIFR_GENERATION_CHUNK_DAYS"
echo "SEIFR_FILTER_FMIN=$SEIFR_FILTER_FMIN"
echo "SEIFR_FILTER_FMAX=$SEIFR_FILTER_FMAX"
echo "SEIFR_DOWNSAMPLE_FACTOR=$SEIFR_DOWNSAMPLE_FACTOR"
echo "SEIFR_GENERATION_MAX_DAYS=${SEIFR_GENERATION_MAX_DAYS:-unset}"
echo "SEIFR_MAX_GENERATION_ENTRIES=${SEIFR_MAX_GENERATION_ENTRIES:-unset}"
echo "SEIFR_GENERATION_ENTRY_OFFSET=$SEIFR_GENERATION_ENTRY_OFFSET"
echo "SEIFR_GENERATION_ENTRY_STRIDE=$SEIFR_GENERATION_ENTRY_STRIDE"
echo "SEIFR_START_DATE=$SEIFR_START_DATE"
echo "SEIFR_DAYS_TO_LOAD=$SEIFR_DAYS_TO_LOAD"
echo "SEIFR_SELECT_NETWORKS=${SEIFR_SELECT_NETWORKS:-unset}"
echo "SEIFR_SELECT_STATIONS=${SEIFR_SELECT_STATIONS:-unset}"
echo "SEIFR_SELECT_LOCATIONS=${SEIFR_SELECT_LOCATIONS:-unset}"
echo "SEIFR_SELECT_CHANNELS=${SEIFR_SELECT_CHANNELS:-unset}"
echo "SEIFR_TEMPLATE_CSV=${SEIFR_TEMPLATE_CSV:-unset}"
echo "SEIFR_TEMPLATE_SOURCE=$SEIFR_TEMPLATE_SOURCE"
echo "SEIFR_TEMPLATE_WINDOW_LENGTH_SEC=$SEIFR_TEMPLATE_WINDOW_LENGTH_SEC"
echo "SEIFR_TEMPLATE_LEAD_TIME_SEC=$SEIFR_TEMPLATE_LEAD_TIME_SEC"
echo "SEIFR_TEMPLATE_CHUNKSIZE=${SEIFR_TEMPLATE_CHUNKSIZE:-unset}"
echo "SEIFR_TEMPLATE_LOG_LIMIT=${SEIFR_TEMPLATE_LOG_LIMIT:-unset}"
echo "SEIFR_ENABLE_INVENTORY_REPORT=$SEIFR_ENABLE_INVENTORY_REPORT"
echo "SEIFR_ENABLE_WAVEFORM_REPORT=$SEIFR_ENABLE_WAVEFORM_REPORT"
echo "SEIFR_ENABLE_TEMPLATE_REPORT=$SEIFR_ENABLE_TEMPLATE_REPORT"
echo "SEIFR_WAVEFORM_PLOT_MAX_POINTS=$SEIFR_WAVEFORM_PLOT_MAX_POINTS"
echo "SEIFR_WAVEFORM_PLOT_POINTS_PER_CHUNK=$SEIFR_WAVEFORM_PLOT_POINTS_PER_CHUNK"
echo "SEIFR_TEMPLATE_REPORT_ROW_PREVIEW_LIMIT=$SEIFR_TEMPLATE_REPORT_ROW_PREVIEW_LIMIT"
echo "SEIFR_TEMPLATE_PLOT_SAMPLE_COUNT=$SEIFR_TEMPLATE_PLOT_SAMPLE_COUNT"
echo "SEIFR_TEMPLATE_PLOT_SEED=$SEIFR_TEMPLATE_PLOT_SEED"
echo "RUN_WAVEFORMS=$RUN_WAVEFORMS"
echo "RUN_TEMPLATES=$RUN_TEMPLATES"

if [[ "$RUN_WAVEFORMS" == "1" ]]; then
    echo ""
    echo ">> Generating waveform binaries"
    python dataprep/seiFR/datagen.py
fi

if [[ "$RUN_TEMPLATES" == "1" ]]; then
    echo ""
    echo ">> Generating template binaries"
    python dataprep/seiFR/readcsvtemplates.py
fi

echo ""
echo "Done."
