#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
JOB_SCRIPT="$SCRIPT_DIR/seifr_datagen_job.sh"

SEIFR_SDS_ROOT="${SEIFR_SDS_ROOT:-/path/to/raw/seifr/SDS/}"
SEIFR_WAVEFORM_OUTPUT_DIR="${SEIFR_WAVEFORM_OUTPUT_DIR:-/path/to/data/seifr/waveforms/}"
SEIFR_TEMPLATE_OUTPUT_DIR="${SEIFR_TEMPLATE_OUTPUT_DIR:-/path/to/data/seifr/templates/}"
SEIFR_EVENTS_QML="${SEIFR_EVENTS_QML:-/path/to/raw/seifr/event.qml}"
SEIFR_SUMMARY_OUTPUT_DIR="${SEIFR_SUMMARY_OUTPUT_DIR:-$SCRIPT_DIR/metadata/}"
SEIFR_SLURM_LOG_DIR="${SEIFR_SLURM_LOG_DIR:-$SCRIPT_DIR/logs}"
SEIFR_CHANNEL_PREFIXES="${SEIFR_CHANNEL_PREFIXES:-BH}"

# Set SEIFR_WAVEFORM_ARRAY="" before running this wrapper for one non-array
# waveform job. The default below mirrors the Maule array split.
SEIFR_WAVEFORM_ARRAY="${SEIFR_WAVEFORM_ARRAY-0-23}"

SEIFR_GENERATION_CHUNK_DAYS="${SEIFR_GENERATION_CHUNK_DAYS:-1}"
SEIFR_FILTER_FMIN="${SEIFR_FILTER_FMIN:-1}"
SEIFR_FILTER_FMAX="${SEIFR_FILTER_FMAX:-10}"
SEIFR_DOWNSAMPLE_FACTOR="${SEIFR_DOWNSAMPLE_FACTOR:-2}"
SEIFR_START_DATE="${SEIFR_START_DATE:-2020-1-1}"
SEIFR_DAYS_TO_LOAD="${SEIFR_DAYS_TO_LOAD:-730}"
SEIFR_ENABLE_INVENTORY_REPORT="${SEIFR_ENABLE_INVENTORY_REPORT:-0}"
SEIFR_ENABLE_WAVEFORM_REPORT="${SEIFR_ENABLE_WAVEFORM_REPORT:-1}"
SEIFR_ENABLE_TEMPLATE_REPORT="${SEIFR_ENABLE_TEMPLATE_REPORT:-1}"
SEIFR_WAVEFORM_PLOT_MAX_POINTS="${SEIFR_WAVEFORM_PLOT_MAX_POINTS:-200000}"
SEIFR_WAVEFORM_PLOT_POINTS_PER_CHUNK="${SEIFR_WAVEFORM_PLOT_POINTS_PER_CHUNK:-4000}"
SEIFR_TEMPLATE_SOURCE="${SEIFR_TEMPLATE_SOURCE:-auto}"
SEIFR_TEMPLATE_WINDOW_LENGTH_SEC="${SEIFR_TEMPLATE_WINDOW_LENGTH_SEC:-120}"
SEIFR_TEMPLATE_LEAD_TIME_SEC="${SEIFR_TEMPLATE_LEAD_TIME_SEC:-2}"
SEIFR_TEMPLATE_REPORT_ROW_PREVIEW_LIMIT="${SEIFR_TEMPLATE_REPORT_ROW_PREVIEW_LIMIT:-20}"
SEIFR_TEMPLATE_PLOT_SAMPLE_COUNT="${SEIFR_TEMPLATE_PLOT_SAMPLE_COUNT:-5}"
SEIFR_TEMPLATE_PLOT_SEED="${SEIFR_TEMPLATE_PLOT_SEED:-0}"

SEIFR_SUBMIT_WAVEFORMS="${SEIFR_SUBMIT_WAVEFORMS:-1}"
SEIFR_SUBMIT_TEMPLATES="${SEIFR_SUBMIT_TEMPLATES:-1}"
SEIFR_TEMPLATES_AFTER_WAVEFORMS="${SEIFR_TEMPLATES_AFTER_WAVEFORMS:-1}"

SEIFR_WAVEFORM_JOB_NAME="${SEIFR_WAVEFORM_JOB_NAME:-seifr-waveforms}"
SEIFR_TEMPLATE_JOB_NAME="${SEIFR_TEMPLATE_JOB_NAME:-seifr-templates}"

mkdir -p \
    "$SEIFR_SLURM_LOG_DIR" \
    "$SEIFR_WAVEFORM_OUTPUT_DIR" \
    "$SEIFR_TEMPLATE_OUTPUT_DIR" \
    "$SEIFR_SUMMARY_OUTPUT_DIR"

if ! command -v sbatch >/dev/null 2>&1; then
    echo "ERROR: sbatch was not found in PATH. Run this wrapper on a Slurm login node." >&2
    exit 1
fi

COMMON_EXPORTS=(
    "SEIFR_SDS_ROOT=$SEIFR_SDS_ROOT"
    "SEIFR_WAVEFORM_OUTPUT_DIR=$SEIFR_WAVEFORM_OUTPUT_DIR"
    "SEIFR_TEMPLATE_OUTPUT_DIR=$SEIFR_TEMPLATE_OUTPUT_DIR"
    "SEIFR_EVENTS_QML=$SEIFR_EVENTS_QML"
    "SEIFR_SUMMARY_OUTPUT_DIR=$SEIFR_SUMMARY_OUTPUT_DIR"
    "SEIFR_SLURM_LOG_DIR=$SEIFR_SLURM_LOG_DIR"
    "SEIFR_CHANNEL_PREFIXES=$SEIFR_CHANNEL_PREFIXES"
    "SEIFR_GENERATION_CHUNK_DAYS=$SEIFR_GENERATION_CHUNK_DAYS"
    "SEIFR_FILTER_FMIN=$SEIFR_FILTER_FMIN"
    "SEIFR_FILTER_FMAX=$SEIFR_FILTER_FMAX"
    "SEIFR_DOWNSAMPLE_FACTOR=$SEIFR_DOWNSAMPLE_FACTOR"
    "SEIFR_START_DATE=$SEIFR_START_DATE"
    "SEIFR_DAYS_TO_LOAD=$SEIFR_DAYS_TO_LOAD"
    "SEIFR_ENABLE_INVENTORY_REPORT=$SEIFR_ENABLE_INVENTORY_REPORT"
    "SEIFR_ENABLE_WAVEFORM_REPORT=$SEIFR_ENABLE_WAVEFORM_REPORT"
    "SEIFR_ENABLE_TEMPLATE_REPORT=$SEIFR_ENABLE_TEMPLATE_REPORT"
    "SEIFR_WAVEFORM_PLOT_MAX_POINTS=$SEIFR_WAVEFORM_PLOT_MAX_POINTS"
    "SEIFR_WAVEFORM_PLOT_POINTS_PER_CHUNK=$SEIFR_WAVEFORM_PLOT_POINTS_PER_CHUNK"
    "SEIFR_TEMPLATE_SOURCE=$SEIFR_TEMPLATE_SOURCE"
    "SEIFR_TEMPLATE_WINDOW_LENGTH_SEC=$SEIFR_TEMPLATE_WINDOW_LENGTH_SEC"
    "SEIFR_TEMPLATE_LEAD_TIME_SEC=$SEIFR_TEMPLATE_LEAD_TIME_SEC"
    "SEIFR_TEMPLATE_REPORT_ROW_PREVIEW_LIMIT=$SEIFR_TEMPLATE_REPORT_ROW_PREVIEW_LIMIT"
    "SEIFR_TEMPLATE_PLOT_SAMPLE_COUNT=$SEIFR_TEMPLATE_PLOT_SAMPLE_COUNT"
    "SEIFR_TEMPLATE_PLOT_SEED=$SEIFR_TEMPLATE_PLOT_SEED"
)

append_if_set() {
    local name="$1"
    local value="${!name:-}"
    if [[ -n "$value" ]]; then
        COMMON_EXPORTS+=("$name=$value")
    fi
}

append_if_set SEIFR_GENERATION_MAX_DAYS
append_if_set SEIFR_MAX_GENERATION_ENTRIES
append_if_set SEIFR_SELECT_NETWORKS
append_if_set SEIFR_SELECT_STATIONS
append_if_set SEIFR_SELECT_LOCATIONS
append_if_set SEIFR_SELECT_CHANNELS
append_if_set SEIFR_TEMPLATE_CSV
append_if_set SEIFR_TEMPLATE_CHUNKSIZE
append_if_set SEIFR_TEMPLATE_LOG_LIMIT

join_by_comma() {
    local IFS=,
    echo "$*"
}

make_export_arg() {
    echo "ALL,$(join_by_comma "$@")"
}

echo "Submitting seiFR generation jobs"
echo "  Slurm logs: $SEIFR_SLURM_LOG_DIR"
echo "  Waveform output: $SEIFR_WAVEFORM_OUTPUT_DIR"
echo "  Template output: $SEIFR_TEMPLATE_OUTPUT_DIR"
echo "  Summary output: $SEIFR_SUMMARY_OUTPUT_DIR"
echo "  Events QML: $SEIFR_EVENTS_QML"
echo "  Waveform array: ${SEIFR_WAVEFORM_ARRAY:-none}"
echo "  Filter/downsample: ${SEIFR_FILTER_FMIN}-${SEIFR_FILTER_FMAX} Hz, factor $SEIFR_DOWNSAMPLE_FACTOR"

waveform_job_id=""
if [[ "$SEIFR_SUBMIT_WAVEFORMS" == "1" ]]; then
    WAVEFORM_EXPORTS=(
        "${COMMON_EXPORTS[@]}"
        "RUN_WAVEFORMS=1"
        "RUN_TEMPLATES=0"
        "SEIFR_RUN_LABEL=waveforms"
    )
    WAVEFORM_SBATCH_ARGS=(
        --parsable
        --job-name="$SEIFR_WAVEFORM_JOB_NAME"
        --output="$SEIFR_SLURM_LOG_DIR/$SEIFR_WAVEFORM_JOB_NAME.%A_%a.out"
        --error="$SEIFR_SLURM_LOG_DIR/$SEIFR_WAVEFORM_JOB_NAME.%A_%a.err"
        --export="$(make_export_arg "${WAVEFORM_EXPORTS[@]}")"
    )
    if [[ -n "$SEIFR_WAVEFORM_ARRAY" ]]; then
        WAVEFORM_SBATCH_ARGS+=(--array="$SEIFR_WAVEFORM_ARRAY")
    fi

    waveform_job_id="$(sbatch "${WAVEFORM_SBATCH_ARGS[@]}" "$JOB_SCRIPT")"
    echo "Submitted waveform job: $waveform_job_id"
    echo "  stdout pattern: $SEIFR_SLURM_LOG_DIR/$SEIFR_WAVEFORM_JOB_NAME.%A_%a.out"
    echo "  stderr pattern: $SEIFR_SLURM_LOG_DIR/$SEIFR_WAVEFORM_JOB_NAME.%A_%a.err"
else
    echo "Skipping waveform submission because SEIFR_SUBMIT_WAVEFORMS=$SEIFR_SUBMIT_WAVEFORMS"
fi

if [[ "$SEIFR_SUBMIT_TEMPLATES" == "1" ]]; then
    TEMPLATE_EXPORTS=(
        "${COMMON_EXPORTS[@]}"
        "RUN_WAVEFORMS=0"
        "RUN_TEMPLATES=1"
        "SEIFR_RUN_LABEL=templates"
    )
    TEMPLATE_SBATCH_ARGS=(
        --parsable
        --job-name="$SEIFR_TEMPLATE_JOB_NAME"
        --output="$SEIFR_SLURM_LOG_DIR/$SEIFR_TEMPLATE_JOB_NAME.%A.out"
        --error="$SEIFR_SLURM_LOG_DIR/$SEIFR_TEMPLATE_JOB_NAME.%A.err"
        --export="$(make_export_arg "${TEMPLATE_EXPORTS[@]}")"
    )
    if [[ "$SEIFR_TEMPLATES_AFTER_WAVEFORMS" == "1" && -n "$waveform_job_id" ]]; then
        TEMPLATE_SBATCH_ARGS+=(--dependency="afterok:$waveform_job_id")
        echo "Template job will wait for waveform job $waveform_job_id"
    fi

    template_job_id="$(sbatch "${TEMPLATE_SBATCH_ARGS[@]}" "$JOB_SCRIPT")"
    echo "Submitted template job: $template_job_id"
    echo "  stdout pattern: $SEIFR_SLURM_LOG_DIR/$SEIFR_TEMPLATE_JOB_NAME.%A.out"
    echo "  stderr pattern: $SEIFR_SLURM_LOG_DIR/$SEIFR_TEMPLATE_JOB_NAME.%A.err"
else
    echo "Skipping template submission because SEIFR_SUBMIT_TEMPLATES=$SEIFR_SUBMIT_TEMPLATES"
fi

echo "Done submitting seiFR generation jobs."
